//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace AboutInheritance
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AboutInheritanceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AboutInheritanceEntities object using the connection string found in the 'AboutInheritanceEntities' section of the application configuration file.
        /// </summary>
        public AboutInheritanceEntities() : base("name=AboutInheritanceEntities", "AboutInheritanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AboutInheritanceEntities object.
        /// </summary>
        public AboutInheritanceEntities(string connectionString) : base(connectionString, "AboutInheritanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AboutInheritanceEntities object.
        /// </summary>
        public AboutInheritanceEntities(EntityConnection connection) : base(connection, "AboutInheritanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Animal> Animals
        {
            get
            {
                if ((_Animals == null))
                {
                    _Animals = base.CreateObjectSet<Animal>("Animals");
                }
                return _Animals;
            }
        }
        private ObjectSet<Animal> _Animals;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Animals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnimals(Animal animal)
        {
            base.AddObject("Animals", animal);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AboutInheritanceModel", Name="Animal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Dog))]
    [KnownTypeAttribute(typeof(Cat))]
    public abstract partial class Animal : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AboutInheritanceModel", Name="Cat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cat : Animal
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cat object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Cat CreateCat(global::System.Int32 id)
        {
            Cat cat = new Cat();
            cat.Id = id;
            return cat;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CatLivesLeft
        {
            get
            {
                return _CatLivesLeft;
            }
            set
            {
                OnCatLivesLeftChanging(value);
                ReportPropertyChanging("CatLivesLeft");
                _CatLivesLeft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CatLivesLeft");
                OnCatLivesLeftChanged();
            }
        }
        private Nullable<global::System.Int32> _CatLivesLeft;
        partial void OnCatLivesLeftChanging(Nullable<global::System.Int32> value);
        partial void OnCatLivesLeftChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AboutInheritanceModel", Name="Dog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dog : Animal
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dog object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Dog CreateDog(global::System.Int32 id)
        {
            Dog dog = new Dog();
            dog.Id = id;
            return dog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DogYearsLeft
        {
            get
            {
                return _DogYearsLeft;
            }
            set
            {
                OnDogYearsLeftChanging(value);
                ReportPropertyChanging("DogYearsLeft");
                _DogYearsLeft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DogYearsLeft");
                OnDogYearsLeftChanged();
            }
        }
        private Nullable<global::System.Int32> _DogYearsLeft;
        partial void OnDogYearsLeftChanging(Nullable<global::System.Int32> value);
        partial void OnDogYearsLeftChanged();

        #endregion
    
    }

    #endregion
    
}
